Adding threshold option to extract_subdomain
CHLNDDEV/OceanMesh2D pull request #177
Opened 2021-01-26 13:33 UTC by krober10nd

* Elements/vertices can be trimmed inside polygons based on topobathymetry.
* This is particularly useful when triming components of the floodplain that aren't likely to be flooded. 
* For example here I trim a region of the floodplain (> -1 m above the geoid) located in a `polygon` and remap all the attributes (nodal attributes and boundaries) back to the trimmed mesh. 
```
polygon = [define polygon coordinates here]; 
[sub,ind]=extract_subdomain(m, polygon,1,0,-1,-1);
sub = map_mesh_properties(sub,ind);
```

2021-01-26 13:34 UTC, krober10nd commented
Perhaps the kwargs of `extract_subdomain` could be specified as name/value pairs instead of fixed position args.

2021-01-26 15:53 UTC, WPringle commented
Yes I agree we should change the kwarg to name/value pairs. Also can you have threshold work both ways or as a range. Often I want to do it so only elements _shallower_ than 250 m are kept, i.e., only continental shelf.

2021-01-26 16:04 UTC, krober10nd commented
> Yes I agree we should change the kwarg to name/value pairs. Also can you have threshold work both ways or as a range. Often I want to do it so only elements shallower than 250 m are kept, i.e., only continental shelf.

Sure that's reasonable. Also, when you do the extraction, you might want to remove singly connected elements there.

2021-01-29 16:55 UTC, WPringle requested changes
Can the threshold parameter be a bit more clearer and also allow for options both ways?
How about change to two parameters, min_depth and max_depth which are easier to understand and also allows for doing a range

2021-01-29 17:09 UTC, WPringle commented
Ok I'm still a little confused about the the description of min_depth and max_depth on the help and how it is actually implemented. I think the way it is implemented is correct; so that if depth is less than the max_depth and more than the min_depth and inside the polygon then it is trimmed. But help is saying max_depth is to keep parts that are sufficiently deep when it should be other way around. Keep the parts that are shallower than max_depth and deeper than min_depth right?

2021-01-29 17:11 UTC, WPringle commented
and change the if statement to be `max_depth ~= +9999` rather than negative

2021-01-29 18:27 UTC, WPringle commented
Can change the max_depth to be sufficiently shallow and min_depth to be sufficiently deep?

2021-01-29 18:38 UTC, WPringle approved these changes

2021-01-29 18:41 UTC, merged